apiVersion: v1
kind: ConfigMap
metadata:
  name: varnish-configmap
  labels:
    app: varnish
data:
  default.vcl: |
    vcl 4.0;
    backend default {
        .host = "nginx-service";
        .port = "8080";
    }
    sub vcl_recv {
        set req.backend_hint = default;
    }
