kind: Deployment
apiVersion: apps/v1
metadata:
  name: application
  namespace: dev02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      volumes:
      - name: azure
          readOnly: false
          shareName: az-storage-name
          secretName: azure-secret
        azureFile:
      containers:
      - name: application
        image: lxecommercecontainerregistry.azurecr.io/test-image
        resources:
          requests:
            cpu: 400m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 8Gi
        env:
        - name: TEST
          valueFrom:
            secretKeyRef:
              name: test
              key: key
        volumeMounts:
        - name: azure
          mountPath: /mnt/data
