apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
  namespace: dev02
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1024Gi
