apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-dev-kv-magento
  namespace: namespace
spec:
  provider: azure
  secretObjects:
  - data:
    - key: key
      objectName: env
    secretName: env
    type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: #"to fill"
    cloudName: AzurePublicCloud
    objects: |
      array:              
        - |
          objectName: test
          objectType: secret                                    
          objectVersion: ""   
    resourceGroup: #"to fill"
    subscriptionId: #"to fill"
    tenantId: #"to fill"



