apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco
  labels:
    app: falco
spec:
  selector:
    matchLabels:
      app: falco
  template:
    metadata:
      labels:
        app: falco
    spec:
      hostPID: true
      containers:
        - name: falco
          image: falcosecurity/falco:latest
          securityContext:
            privileged: true
          volumeMounts:
            - name: host-root
              mountPath: /host
          env:
            - name: HOST_ROOT
              value: /host
      volumes:
        - name: host-root
          hostPath:
            path: /
