apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev02-azurefile
  namespace: dev02
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: lxdevecommerce02-magento
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
