apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev02-azurefile
  namespace: dev02
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
