apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - image: centos
    name: mypod
    volumeMounts:
      - name: azure
        mountPath: /var/www/html
  volumes:
  - name: azure
    persistentVolumeClaim:
      claimName: azurefile
